Script started on Tue 22 Aug 2023 05:33:59 PM EDT
]777;notify;Command completed;exit]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[?1034h[sjakka@localhost ~]$ man pwd
[?1049h[?1h=PWD(1)                                                                                          User Commands                                                                                          PWD(1)[m
[m
[1mNAME[0m[m
       pwd - print name of current/working directory[m
[m
[1mSYNOPSIS[0m[m
       [1mpwd[0m [[4mOPTION[24m]...[m
[m
[1mDESCRIPTION[0m[m
       Print the full filename of the current working directory.[m
[m
       [1m-L[0m, [1m--logical[0m[m
              use PWD from environment, even if it contains symlinks[m
[m
       [1m-P[0m, [1m--physical[0m[m
              avoid all symlinks[m
[m
       [1m--help[0m display this help and exit[m
[m
       [1m--version[0m[m
              output version information and exit[m
[m
       NOTE: your shell may have its own version of pwd, which usually supersedes the version described here.  Please refer to your shell's documentation for details about the options it supports.[m
[m
       GNU coreutils online help: <http://www.gnu.org/software/coreutils/> Report pwd translation bugs to <http://translationproject.org/team/>[m
[m
[1mAUTHOR[0m[m
       Written by Jim Meyering.[m
[m
[1mCOPYRIGHT[0m[m
       Copyright © 2013 Free Software Foundation, Inc.  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.[m
       This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.[m
[m
[1mSEE[0m [1mALSO[0m[m
       getcwd(3)[m
[m
       The full documentation for [1mpwd[0m is maintained as a Texinfo manual.  If the [1minfo[0m and [1mpwd[0m programs are properly installed at your site, the command[m
[m
              [1minfo[0m [1mcoreutils[0m [1m'pwd[0m [1minvocation'[0m[m
[m
       should give you access to the complete manual.[m
[m
GNU coreutils 8.22                                                                              November 2020                                                                                          PWD(1)[m
[7m Manual page pwd(1) line 1/47 (END) (press h for help or q to quit)[27m[K[K[?1l>[?1049l]777;notify;Command completed;man pwd]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ nproc
1
]777;notify;Command completed;nproc]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ top
[?1h=[?25l[H[2J(B[mtop - 17:34:48 up 28 min,  3 users,  load average: 0.04, 0.04, 0.14(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 227 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 226 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  6.2 (B[m[39;49mus,(B[m[39;49m[1m  6.2 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 87.5 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m   995460 (B[m[39;49mtotal,(B[m[39;49m[1m    69712 (B[m[39;49mfree,(B[m[39;49m[1m   680812 (B[m[39;49mused,(B[m[39;49m[1m   244936 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  2097148 (B[m[39;49mtotal,(B[m[39;49m[1m  1677308 (B[m[39;49mfree,(B[m[39;49m[1m   419840 (B[m[39;49mused.(B[m[39;49m[1m   100688 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                        (B[m[39;49m[K
(B[m  2087 sjakka    20   0 3071844 174648  44408 S  6.2 17.5   0:39.74 gnome-shell                                                                                                                                    (B[m[39;49m[K
(B[m     1 root      20   0  193964   4452   2512 S  0.0  0.4   0:02.40 systemd                                                                                                                                        (B[m[39;49m[K
(B[m     2 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kthreadd                                                                                                                                       (B[m[39;49m[K
(B[m     4 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/0:0H                                                                                                                                   (B[m[39;49m[K
(B[m     6 root      20   0       0      0      0 S  0.0  0.0   0:00.10 ksoftirqd/0                                                                                                                                    (B[m[39;49m[K
(B[m     7 root      rt   0       0      0      0 S  0.0  0.0   0:00.00 migration/0                                                                                                                                    (B[m[39;49m[K
(B[m     8 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcu_bh                                                                                                                                         (B[m[39;49m[K
(B[m     9 root      20   0       0      0      0 S  0.0  0.0   0:00.55 rcu_sched                                                                                                                                      (B[m[39;49m[K
(B[m    10 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 lru-add-drain                                                                                                                                  (B[m[39;49m[K
(B[m    11 root      rt   0       0      0      0 S  0.0  0.0   0:00.02 watchdog/0                                                                                                                                     (B[m[39;49m[K
(B[m    13 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kdevtmpfs                                                                                                                                      (B[m[39;49m[K
(B[m    14 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 netns                                                                                                                                          (B[m[39;49m[K
(B[m    15 root      20   0       0      0      0 S  0.0  0.0   0:00.00 khungtaskd                                                                                                                                     (B[m[39;49m[K
(B[m    16 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 writeback                                                                                                                                      (B[m[39;49m[K
(B[m    17 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kintegrityd                                                                                                                                    (B[m[39;49m[K
(B[m    18 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset                                                                                                                                         (B[m[39;49m[K
(B[m    19 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset                                                                                                                                         (B[m[39;49m[K
(B[m    20 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset                                                                                                                                         (B[m[39;49m[K
(B[m    21 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kblockd                                                                                                                                        (B[m[39;49m[K
(B[m    22 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 md                                                                                                                                             (B[m[39;49m[K
(B[m    23 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 edac-poller                                                                                                                                    (B[m[39;49m[K
(B[m    24 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 watchdogd                                                                                                                                      (B[m[39;49m[K
(B[m    30 root      20   0       0      0      0 S  0.0  0.0   0:05.37 kswapd0                                                                                                                                        (B[m[39;49m[K
(B[m    31 root      25   5       0      0      0 S  0.0  0.0   0:00.00 ksmd                                                                                                                                           (B[m[39;49m[K
(B[m    32 root      39  19       0      0      0 S  0.0  0.0   0:00.00 khugepaged                                                                                                                                     (B[m[39;49m[K
(B[m    33 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 crypto                                                                                                                                         (B[m[39;49m[K
(B[m    41 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kthrotld                                                                                                                                       (B[m[39;49m[K
(B[m    42 root      20   0       0      0      0 S  0.0  0.0   0:00.08 kworker/u256:1                                                                                                                                 (B[m[39;49m[K
(B[m    43 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kmpath_rdacd                                                                                                                                   (B[m[39;49m[K
(B[m    44 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kaluad                                                                                                                                         (B[m[39;49m[K
(B[m    45 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kpsmoused                                                                                                                                      (B[m[39;49m[K
(B[m    47 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 ipv6_addrconf                                                                                                                                  (B[m[39;49m[K
(B[m    60 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 deferwq                                                                                                                                        (B[m[39;49m[K
(B[m    95 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kauditd                                                                                                                                        (B[m[39;49m[K
(B[m   282 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 mpt_poll_0                                                                                                                                     (B[m[39;49m[K
(B[m   283 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 ata_sff                                                                                                                                        (B[m[39;49m[K
(B[m   284 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 mpt/0                                                                                                                                          (B[m[39;49m[K
(B[m   288 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 nfit                                                                                                                                           (B[m[39;49m[K
(B[m   289 root      20   0       0      0      0 S  0.0  0.0   0:00.00 scsi_eh_0                                                                                                                                      (B[m[39;49m[K[H(B[mtop - 17:34:51 up 28 min,  3 users,  load average: 0.04, 0.04, 0.14(B[m[39;49m(B[m[39;49m[K

%Cpu(s):(B[m[39;49m[1m  1.7 (B[m[39;49mus,(B[m[39;49m[1m  0.0 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 98.3 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m   995460 (B[m[39;49mtotal,(B[m[39;49m[1m    69712 (B[m[39;49mfree,(B[m[39;49m[1m   680792 (B[m[39;49mused,(B[m[39;49m[1m   244956 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  2097148 (B[m[39;49mtotal,(B[m[39;49m[1m  1677308 (B[m[39;49mfree,(B[m[39;49m[1m   419840 (B[m[39;49mused.(B[m[39;49m[1m   100732 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K

(B[m  2087 sjakka    20   0 3071844 174648  44408 S  0.7 17.5   0:39.76 gnome-shell                                                                                                                                    (B[m[39;49m[K
(B[m     9 root      20   0       0      0      0 S  0.3  0.0   0:00.56 rcu_sched                                                                                                                                      (B[m[39;49m[K
(B[m  1368 root      20   0  410868 102252  56060 S  0.3 10.3   0:14.51 X                                                                                                                                              (B[m[39;49m[K
(B[m  3210 sjakka    20   0  673076  18756   6304 S  0.3  1.9   0:04.85 gnome-terminal-                                                                                                                                (B[m[39;49m[K
(B[m     1 root      20   0  193964   4452   2512 S  0.0  0.4   0:02.40 systemd                                                                                                                                        (B[m[39;49m[K
(B[m     2 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kthreadd                                                                                                                                       (B[m[39;49m[K
(B[m     4 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/0:0H                                                                                                                                   (B[m[39;49m[K
(B[m     6 root      20   0       0      0      0 S  0.0  0.0   0:00.10 ksoftirqd/0                                                                                                                                    (B[m[39;49m[K
(B[m     7 root      rt   0       0      0      0 S  0.0  0.0   0:00.00 migration/0                                                                                                                                    (B[m[39;49m[K
(B[m     8 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcu_bh                                                                                                                                         (B[m[39;49m[K
(B[m    10 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 lru-add-drain                                                                                                                                  (B[m[39;49m[K
(B[m    11 root      rt   0       0      0      0 S  0.0  0.0   0:00.02 watchdog/0                                                                                                                                     (B[m[39;49m[K
(B[m    13 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kdevtmpfs                                                                                                                                      (B[m[39;49m[K
(B[m    14 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 netns                                                                                                                                          (B[m[39;49m[K
(B[m    15 root      20   0       0      0      0 S  0.0  0.0   0:00.00 khungtaskd                                                                                                                                     (B[m[39;49m[K
(B[m    16 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 writeback                                                                                                                                      (B[m[39;49m[K
(B[m    17 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kintegrityd                                                                                                                                    (B[m[39;49m[K
(B[m    18 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset                                                                                                                                         (B[m[39;49m[K
(B[m    19 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset                                                                                                                                         (B[m[39;49m[K
(B[m    20 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset                                                                                                                                         (B[m[39;49m[K
(B[m    21 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kblockd                                                                                                                                        (B[m[39;49m[K
(B[m    22 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 md                                                                                                                                             (B[m[39;49m[K
(B[m    23 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 edac-poller                                                                                                                                    (B[m[39;49m[K
(B[m    24 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 watchdogd                                                                                                                                      (B[m[39;49m[K
(B[m    30 root      20   0       0      0      0 S  0.0  0.0   0:05.37 kswapd0                                                                                                                                        (B[m[39;49m[K
(B[m    31 root      25   5       0      0      0 S  0.0  0.0   0:00.00 ksmd                                                                                                                                           (B[m[39;49m[K
(B[m    32 root      39  19       0      0      0 S  0.0  0.0   0:00.00 khugepaged                                                                                                                                     (B[m[39;49m[K
(B[m    33 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 crypto                                                                                                                                         (B[m[39;49m[K
(B[m    41 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kthrotld                                                                                                                                       (B[m[39;49m[K
(B[m    42 root      20   0       0      0      0 S  0.0  0.0   0:00.08 kworker/u256:1                                                                                                                                 (B[m[39;49m[K
(B[m    43 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kmpath_rdacd                                                                                                                                   (B[m[39;49m[K
(B[m    44 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kaluad                                                                                                                                         (B[m[39;49m[K
(B[m    45 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kpsmoused                                                                                                                                      (B[m[39;49m[K
(B[m    47 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 ipv6_addrconf                                                                                                                                  (B[m[39;49m[K
(B[m    60 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 deferwq                                                                                                                                        (B[m[39;49m[K
(B[m    95 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kauditd                                                                                                                                        (B[m[39;49m[K
(B[m   282 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 mpt_poll_0                                                                                                                                     (B[m[39;49m[K
(B[m   283 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 ata_sff                                                                                                                                        (B[m[39;49m[K
(B[m   284 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 mpt/0                                                                                                                                          (B[m[39;49m[K[H(B[mtop - 17:34:54 up 28 min,  3 users,  load average: 0.04, 0.04, 0.14(B[m[39;49m(B[m[39;49m[K

%Cpu(s):(B[m[39;49m[1m  8.9 (B[m[39;49mus,(B[m[39;49m[1m  1.7 (B[m[39;49msy,(B[m[39;49m[1m  2.4 (B[m[39;49mni,(B[m[39;49m[1m 87.0 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m   995460 (B[m[39;49mtotal,(B[m[39;49m[1m    69696 (B[m[39;49mfree,(B[m[39;49m[1m   680828 (B[m[39;49mused,(B[m[39;49m[1m   244936 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  2097148 (B[m[39;49mtotal,(B[m[39;49m[1m  1677308 (B[m[39;49mfree,(B[m[39;49m[1m   419840 (B[m[39;49mused.(B[m[39;49m[1m   100748 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K

(B[m  2087 sjakka    20   0 3071844 174648  44408 S  6.0 17.5   0:39.94 gnome-shell                                                                                                                                    (B[m[39;49m[K
(B[m  1368 root      20   0  410868 102252  56060 S  3.7 10.3   0:14.62 X                                                                                                                                              (B[m[39;49m[K
(B[m  2467 sjakka    39  19  736644   4272   1992 S  2.3  0.4   0:01.49 tracker-extract                                                                                                                                (B[m[39;49m[K
(B[m  3210 sjakka    20   0  673076  18756   6304 S  2.0  1.9   0:04.91 gnome-terminal-                                                                                                                                (B[m[39;49m[K
(B[m  2948 sjakka    20   0 1122.3g  54548  14188 S  0.7  5.5   0:05.98 code                                                                                                                                           (B[m[39;49m[K
(B[m[1m  4344 sjakka    20   0  162120   2404   1584 R  0.7  0.2   0:00.03 top                                                                                                                                            (B[m[39;49m[K
(B[m   407 root      20   0       0      0      0 S  0.3  0.0   0:00.69 xfsaild/dm-0                                                                                                                                   (B[m[39;49m[K
(B[m   712 root      20   0   90668    128    128 S  0.3  0.0   0:01.78 rngd                                                                                                                                           (B[m[39;49m[K
(B[m   724 root      20   0  360916   1644   1232 S  0.3  0.2   0:02.37 vmtoolsd                                                                                                                                       (B[m[39;49m[K
(B[m  2416 sjakka    20   0  608812   3548   1616 S  0.3  0.4   0:02.64 vmtoolsd                                                                                                                                       (B[m[39;49m[K
(B[m  2503 sjakka    20   0  591404   7520   2308 S  0.3  0.8   0:00.40 tracker-store                                                                                                                                  (B[m[39;49m[K
(B[m     1 root      20   0  193964   4452   2512 S  0.0  0.4   0:02.40 systemd                                                                                                                                        (B[m[39;49m[K
(B[m     2 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kthreadd                                                                                                                                       (B[m[39;49m[K
(B[m     4 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/0:0H                                                                                                                                   (B[m[39;49m[K
(B[m     6 root      20   0       0      0      0 S  0.0  0.0   0:00.10 ksoftirqd/0                                                                                                                                    (B[m[39;49m[K
(B[m     7 root      rt   0       0      0      0 S  0.0  0.0   0:00.00 migration/0                                                                                                                                    (B[m[39;49m[K
(B[m     8 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcu_bh                                                                                                                                         (B[m[39;49m[K
(B[m     9 root      20   0       0      0      0 S  0.0  0.0   0:00.56 rcu_sched                                                                                                                                      (B[m[39;49m[K
(B[m    10 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 lru-add-drain                                                                                                                                  (B[m[39;49m[K
(B[m    11 root      rt   0       0      0      0 S  0.0  0.0   0:00.02 watchdog/0                                                                                                                                     (B[m[39;49m[K
(B[m    13 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kdevtmpfs                                                                                                                                      (B[m[39;49m[K
(B[m    14 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 netns                                                                                                                                          (B[m[39;49m[K
(B[m    15 root      20   0       0      0      0 S  0.0  0.0   0:00.00 khungtaskd                                                                                                                                     (B[m[39;49m[K
(B[m    16 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 writeback                                                                                                                                      (B[m[39;49m[K
(B[m    17 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kintegrityd                                                                                                                                    (B[m[39;49m[K
(B[m    18 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset                                                                                                                                         (B[m[39;49m[K
(B[m    19 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset                                                                                                                                         (B[m[39;49m[K
(B[m    20 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset                                                                                                                                         (B[m[39;49m[K
(B[m    21 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kblockd                                                                                                                                        (B[m[39;49m[K
(B[m    22 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 md                                                                                                                                             (B[m[39;49m[K
(B[m    23 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 edac-poller                                                                                                                                    (B[m[39;49m[K
(B[m    24 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 watchdogd                                                                                                                                      (B[m[39;49m[K
(B[m    30 root      20   0       0      0      0 S  0.0  0.0   0:05.37 kswapd0                                                                                                                                        (B[m[39;49m[K
(B[m    31 root      25   5       0      0      0 S  0.0  0.0   0:00.00 ksmd                                                                                                                                           (B[m[39;49m[K
(B[m    32 root      39  19       0      0      0 S  0.0  0.0   0:00.00 khugepaged                                                                                                                                     (B[m[39;49m[K
(B[m    33 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 crypto                                                                                                                                         (B[m[39;49m[K
(B[m    41 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kthrotld                                                                                                                                       (B[m[39;49m[K
(B[m    42 root      20   0       0      0      0 S  0.0  0.0   0:00.08 kworker/u256:1                                                                                                                                 (B[m[39;49m[K
(B[m    43 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kmpath_rdacd                                                                                                                                   (B[m[39;49m[K[H(B[mtop - 17:34:57 up 28 min,  3 users,  load average: 0.03, 0.04, 0.13(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 227 (B[m[39;49mtotal,(B[m[39;49m[1m   2 (B[m[39;49mrunning,(B[m[39;49m[1m 225 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  4.9 (B[m[39;49mus,(B[m[39;49m[1m  1.8 (B[m[39;49msy,(B[m[39;49m[1m  0.4 (B[m[39;49mni,(B[m[39;49m[1m 92.9 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m   995460 (B[m[39;49mtotal,(B[m[39;49m[1m    69680 (B[m[39;49mfree,(B[m[39;49m[1m   680792 (B[m[39;49mused,(B[m[39;49m[1m   244988 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  2097148 (B[m[39;49mtotal,(B[m[39;49m[1m  1677308 (B[m[39;49mfree,(B[m[39;49m[1m   419840 (B[m[39;49mused.(B[m[39;49m[1m   100732 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K

(B[m[1m  1368 root      20   0  410868 102252  56060 R  4.0 10.3   0:14.74 X                                                                                                                                              (B[m[39;49m[K
(B[m  2087 sjakka    20   0 3071844 174648  44408 S  3.0 17.5   0:40.03 gnome-shell                                                                                                                                    (B[m[39;49m[K
(B[m  3210 sjakka    20   0  673076  18756   6304 S  2.3  1.9   0:04.98 gnome-terminal-                                                                                                                                (B[m[39;49m[K
(B[m  2948 sjakka    20   0 1122.3g  54548  14188 S  0.3  5.5   0:05.99 code                                                                                                                                           (B[m[39;49m[K
(B[m  4036 root      20   0       0      0      0 S  0.3  0.0   0:00.25 kworker/0:2                                                                                                                                    (B[m[39;49m[K
(B[m     1 root      20   0  193964   4452   2512 S  0.0  0.4   0:02.40 systemd                                                                                                                                        (B[m[39;49m[K
(B[m     2 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kthreadd                                                                                                                                       (B[m[39;49m[K
(B[m     4 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/0:0H                                                                                                                                   (B[m[39;49m[K
(B[m     6 root      20   0       0      0      0 S  0.0  0.0   0:00.10 ksoftirqd/0                                                                                                                                    (B[m[39;49m[K
(B[m     7 root      rt   0       0      0      0 S  0.0  0.0   0:00.00 migration/0                                                                                                                                    (B[m[39;49m[K
(B[m     8 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcu_bh                                                                                                                                         (B[m[39;49m[K
(B[m     9 root      20   0       0      0      0 S  0.0  0.0   0:00.56 rcu_sched                                                                                                                                      (B[m[39;49m[K
(B[m    10 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 lru-add-drain                                                                                                                                  (B[m[39;49m[K
(B[m    11 root      rt   0       0      0      0 S  0.0  0.0   0:00.02 watchdog/0                                                                                                                                     (B[m[39;49m[K
(B[m    13 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kdevtmpfs                                                                                                                                      (B[m[39;49m[K
(B[m    14 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 netns                                                                                                                                          (B[m[39;49m[K
(B[m    15 root      20   0       0      0      0 S  0.0  0.0   0:00.00 khungtaskd                                                                                                                                     (B[m[39;49m[K
(B[m    16 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 writeback                                                                                                                                      (B[m[39;49m[K
(B[m    17 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kintegrityd                                                                                                                                    (B[m[39;49m[K
(B[m    18 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset                                                                                                                                         (B[m[39;49m[K
(B[m    19 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset                                                                                                                                         (B[m[39;49m[K
(B[m    20 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset                                                                                                                                         (B[m[39;49m[K
(B[m    21 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kblockd                                                                                                                                        (B[m[39;49m[K
(B[m    22 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 md                                                                                                                                             (B[m[39;49m[K
(B[m    23 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 edac-poller                                                                                                                                    (B[m[39;49m[K
(B[m    24 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 watchdogd                                                                                                                                      (B[m[39;49m[K
(B[m    30 root      20   0       0      0      0 S  0.0  0.0   0:05.37 kswapd0                                                                                                                                        (B[m[39;49m[K
(B[m    31 root      25   5       0      0      0 S  0.0  0.0   0:00.00 ksmd                                                                                                                                           (B[m[39;49m[K
(B[m    32 root      39  19       0      0      0 S  0.0  0.0   0:00.00 khugepaged                                                                                                                                     (B[m[39;49m[K
(B[m    33 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 crypto                                                                                                                                         (B[m[39;49m[K
(B[m    41 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kthrotld                                                                                                                                       (B[m[39;49m[K
(B[m    42 root      20   0       0      0      0 S  0.0  0.0   0:00.08 kworker/u256:1                                                                                                                                 (B[m[39;49m[K
(B[m    43 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kmpath_rdacd                                                                                                                                   (B[m[39;49m[K
(B[m    44 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kaluad                                                                                                                                         (B[m[39;49m[K
(B[m    45 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kpsmoused                                                                                                                                      (B[m[39;49m[K
(B[m    47 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 ipv6_addrconf                                                                                                                                  (B[m[39;49m[K
(B[m    60 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 deferwq                                                                                                                                        (B[m[39;49m[K
(B[m    95 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kauditd                                                                                                                                        (B[m[39;49m[K
(B[m   282 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 mpt_poll_0                                                                                                                                     (B[m[39;49m[K[?1l>[47;1H
[?12l[?25h[K]777;notify;Command completed;top]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ ls
commands.script  [0m[38;5;27mDesktop[0m  [38;5;27mDocuments[0m  [38;5;27mDownloads[0m  [38;5;27mMusic[0m  [38;5;27mPictures[0m  [38;5;27mPublic[0m  [38;5;34msimple[0m  simple.c  [38;5;27mTemplates[0m  Test.txt  typescript  [38;5;27mVideos[0m
]777;notify;Command completed;ls]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ pwd
/home/sjakka
]777;notify;Command completed;pwd]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ mkdir TestDIre[K[K[Kirecort[K[K[Ktory
]777;notify;Command completed;mkdir TestDirectory]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ ls
commands.script  [0m[38;5;27mDesktop[0m  [38;5;27mDocuments[0m  [38;5;27mDownloads[0m  [38;5;27mMusic[0m  [38;5;27mPictures[0m  [38;5;27mPublic[0m  [38;5;34msimple[0m  simple.c  [38;5;27mTemplates[0m  [38;5;27mTestDirectory[0m  Test.txt  typescript  [38;5;27mVideos[0m
]777;notify;Command completed;ls]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ who [K
sjakka   :0           2023-08-22 17:07 (:0)
sjakka   pts/0        2023-08-22 17:09 (:0)
sjakka   pts/1        2023-08-22 17:33
]777;notify;Command completed;who]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ chmod[K[K[K[K[Kls -l Test.txt
-rw-------. 1 sjakka sjakka 0 Aug 22 17:21 Test.txt
]777;notify;Command completed;ls -l Test.txt]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ chmod 666 TEst.[K[K[K[Kest.txt
]777;notify;Command completed;chmod 666 Test.txt]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ chmod 666 Test.txt[4Pls -l[C[C[C[C[C[C[C[C[C
-rw-rw-rw-. 1 sjakka sjakka 0 Aug 22 17:21 Test.txt
]777;notify;Command completed;ls -l Test.txt]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ Te[K[Kmx [K[Kv test.txt TestDIre[K[K[Kirectory
mv: cannot stat ‘test.txt’: No such file or directory
]777;notify;Command completed;mv test.txt TestDirectory]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ mv Test,[K.txt TEst[K[K[Ke
Templates/     TestDirectory/ Test.txt       
[sjakka@localhost ~]$ mv Test.txt Te
Templates/     TestDirectory/ Test.txt       
[sjakka@localhost ~]$ mv Test.txt TestDIre[K[K[Kirectory
]777;notify;Command completed;mv Test.txt TestDirectory]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ ls
commands.script  [0m[38;5;27mDesktop[0m  [38;5;27mDocuments[0m  [38;5;27mDownloads[0m  [38;5;27mMusic[0m  [38;5;27mPictures[0m  [38;5;27mPublic[0m  [38;5;34msimple[0m  simple.c  [38;5;27mTemplates[0m  [38;5;27mTestDirectory[0m  typescript  [38;5;27mVideos[0m
]777;notify;Command completed;ls]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ cd TEst[K[K[KestDI[Kirectory/[K
]777;notify;Command completed;cd TestDirectory]0;sjakka@localhost:~/TestDirectory]7;file://localhost.localdomain/home/sjakka/TestDirectory[sjakka@localhost TestDirectory]$ ls
Test.txt
]777;notify;Command completed;ls]0;sjakka@localhost:~/TestDirectory]7;file://localhost.localdomain/home/sjakka/TestDirectory[sjakka@localhost TestDirectory]$ cp TEst.[K[K[K[Kest.txt ../
]777;notify;Command completed;cp Test.txt ../]0;sjakka@localhost:~/TestDirectory]7;file://localhost.localdomain/home/sjakka/TestDirectory[sjakka@localhost TestDirectory]$ cd ..
]777;notify;Command completed;cd ..]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ ls
commands.script  [0m[38;5;27mDesktop[0m  [38;5;27mDocuments[0m  [38;5;27mDownloads[0m  [38;5;27mMusic[0m  [38;5;27mPictures[0m  [38;5;27mPublic[0m  [38;5;34msimple[0m  simple.c  [38;5;27mTemplates[0m  [38;5;27mTestDirectory[0m  Test.txt  typescript  [38;5;27mVideos[0m
]777;notify;Command completed;ls]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ cd TestDI[Kirectory/[K
]777;notify;Command completed;cd TestDirectory]0;sjakka@localhost:~/TestDirectory]7;file://localhost.localdomain/home/sjakka/TestDirectory[sjakka@localhost TestDirectory]$ rmdir [K[K[K[K [K[K[Kls
Test.txt
]777;notify;Command completed;ls]0;sjakka@localhost:~/TestDirectory]7;file://localhost.localdomain/home/sjakka/TestDirectory[sjakka@localhost TestDirectory]$ rm Test.txt 
]777;notify;Command completed;rm Test.txt ]0;sjakka@localhost:~/TestDirectory]7;file://localhost.localdomain/home/sjakka/TestDirectory[sjakka@localhost TestDirectory]$ cd ..
]777;notify;Command completed;cd ..]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ rmdir TestDirectory/[K
]777;notify;Command completed;rmdir TestDirectory]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ ls
commands.script  [0m[38;5;27mDesktop[0m  [38;5;27mDocuments[0m  [38;5;27mDownloads[0m  [38;5;27mMusic[0m  [38;5;27mPictures[0m  [38;5;27mPublic[0m  [38;5;34msimple[0m  simple.c  [38;5;27mTemplates[0m  Test.txt  typescript  [38;5;27mVideos[0m
]777;notify;Command completed;ls]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ clear
[3;J[H[2J]777;notify;Command completed;clear]0;sjakka@localhost:~]7;file://localhost.localdomain/home/sjakka[sjakka@localhost ~]$ exit
exit

Script done on Tue 22 Aug 2023 05:42:44 PM EDT
